"""
Django settings for rabbit project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mlvawq4hpnoex78@xpc_s5@nh)554zp)n&0=9b48(2g#5j*io^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MANAGERS = (('Jose', 'jose@haushaus.mx'),('Jhon', 'Jhon@roof.mx'))

DYNAMIC_FORMS_EMAIL_RECIPIENTS = ['backup@haushaus.mx']

DEFAULT_FROM_EMAIL = 'admin@haushaus.mx'




# Application definition

INSTALLED_APPS = (
    'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'captcha',
    'content',
    'mptt',
    'django_mptt_admin',
    'sorl.thumbnail',
    'dynamic_forms',
    'dynamic_forms.contrib.simple_captcha',
    'widget_tweaks',
    'taggit',
    'nocaptcha_recaptcha',
    'secretballot',
    'likes',
    'feedback_form'
)

# App configs

#taggit
TAGGIT_CASE_INSENSITIVE = True

NORECAPTCHA_SITE_KEY = '6LeptgsTAAAAACAC2Qpdyep_I9gTy1S-K0G10VzK'

NORECAPTCHA_SECRET_KEY = '6LeptgsTAAAAAFHCHMmgqCH-62kigxG2BF_rhKxS'

#feedback
FROM_EMAIL = 'feedback@roof.mx'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'dynamic_forms.middlewares.FormModelMiddleware',
    'secretballot.middleware.SecretBallotIpUseragentMiddleware',
    'likes.middleware.SecretBallotUserIpUseragentMiddleware',
)

ROOT_URLCONF = 'rabbit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'content.context_processors.get_category_nodes',
                "django.core.context_processors.media",
                "django.core.context_processors.static",
                'django.core.context_processors.request',

            ],
        },
    },
]

#------- Message-boostrap compatibility---------------------
from django.contrib.messages import constants as message_constants
MESSAGE_TAGS = {message_constants.DEBUG: 'debug',
                message_constants.INFO: 'info',
                message_constants.SUCCESS: 'success',
                message_constants.WARNING: 'warning',
                message_constants.ERROR: 'danger'}

WSGI_APPLICATION = 'rabbit.wsgi.application'

SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-MX'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

try:
    from settings_local import *
except ImportError:
    pass
